name: swafe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Logo_SWAFE_Size_250x250.png"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  flutter_bloc: ^8.1.3
  email_validator: ^2.1.17
  flutter_keyboard_visibility: ^5.4.1
  firebase_auth: ^4.9.0
  fluro: ^2.0.5
  url_launcher: ^6.1.13
  url_launcher_ios: ^6.1.5
  cloud_firestore: ^4.9.1
  google_fonts: ^6.0.0
  dartleaf: ^1.1.4
  firebase_database: ^10.2.5
  flutter_map: ^6.0.1
  latlng: ^1.0.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.2.0
  location: ^5.0.3
  geolocator: ^10.0.1
  permission_handler: ^11.0.0
  app_settings: ^5.0.0
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  google_places_flutter: ^2.0.7
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  face_camera: ^0.0.9
  http: ^1.2.0
  mime: ^1.0.5
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env